# Generated by Django 2.2 on 2020-04-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createform',
            old_name='favouriteColour',
            new_name='favourite_colour',
        ),
    ]
